### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by moteus** [keplerproject/luacov#11]
I have idea about implement `test` reporter to allow unit testing luacov.
This is my [basic variant](https://github.com/moteus/luacov/tree/unit_test) and [travis log](https://travis-ci.org/moteus/luacov).
Basically you just mark Lua code with `-- @LUACOV_TEST <MARK>` in test file and 
run `luacov -r test`. Mark is on of EMPTY, MISSED, HIT.
May be some one hase idea about better line marks and output format, or integration with lunit/busted?

**Comment by mpeterv** [comment]
This is sort of fixed by @53ee3d2?

**Comment by mpeterv** [comment]
There are also full CLI tests now that also test which lines are covered.
