### ISSUE TITLE
include list is matched against without .lua

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luacov#22]
Need to document the fact that you have to leave `.lua` off the file names in the include list.

**Comment by mpeterv** [comment]
Isn't it mentioned in the default options? https://github.com/keplerproject/luacov/blob/10f59c6edc9425ca066076e3d8ada32f39073549/src/luacov/defaults.lua#L37-L38

**Comment by daurnimator** [comment]
hrm. it appears so... not sure why I didn't see that.
