### ISSUE TITLE
How to work with coroutines?

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luacov#38]
How can/should I use luacov with coroutine heavy programs?
(In PUC-Rio Lua, debug hooks are per-coroutine)

**Comment by mpeterv** [comment]
luacov patches global coroutine.create and coroutine.wrap so that coroutines they produce have the debug hook on.

**Comment by daurnimator** [comment]
Thats good to know. 

However, in my case, the coroutines are being created in C. What should I do?

**Comment by mpeterv** [comment]
Assuming you control coroutine creation or can access all coroutines created from C, you could get the debug hook luacov uses using debug.gethook on the main thread, then set it on each coroutine. Perhaps luacov should expose a function for that...

**Comment by daurnimator** [comment]
To be more specific, I'm trying to profile some code that uses cqueues.
The `cq:wrap` method takes a function, turns it into a coroutine, adds it to the scheduler `cq`.
https://github.com/wahern/cqueues/blob/faa63dc4593c6ce8c7774a6f0e8bc583b18ebbd4/src/cqueues.c#L2331
How could/should this function be changed to be "luacov friendly"?

**Comment by hishamhm** [comment]
> In PUC-Rio Lua, debug hooks are per-coroutine

And it isn't it so in LuaJIT? (I wasn't aware!) Maybe the simples thing is just to test coverage using that instead?

**Comment by daurnimator** [comment]
> And it isn't it so in LuaJIT? (I wasn't aware!) 

From http://luajit.org/status.html
> The Lua debug API is missing a couple of features (return hooks for non-Lua functions) and shows slightly different behavior in LuaJIT (no per-coroutine hooks, no tail call counting).

> Maybe the simples thing is just to test coverage using that instead?

Not when my code uses 5.3 features :)

**Comment by mpeterv** [comment]
@daurnimator you could get debug hook in the main chunk and set it in the beginning of functions passed to cq:wrap():

```lua
local hook, mask = debug.gethook()
...
cq:wrap(function() debug.sethook(hook, mask) ... end)
```

**Comment by daurnimator** [comment]
> @daurnimator you could get debug hook in the main chunk and set it in the beginning of functions passed to cq:wrap():

Interesting..... but hard to place into a library.

I'm wondering if there's a reasonable place to put something like this:
```lua
	if not jit then -- LuaJIT does not support per-coroutine debug hooks
		local wrap; wrap = cqueues.interpose("wrap", function (self, func, ...)
			local hook, mask, count = debug.gethook()
			return wrap(self, function (...)
				debug.sethook(hook, mask, count)
				return func(...)
			end, ...)
		end)
	end
```
(`interpose` is a method provided on cqueues objects for extending the class)

BTW, this whole issue is something I brought up with Roberto in stockholm: having something like `luai_userstatethread` that you can provide via the debug library.

**Comment by mpeterv** [comment]
@daurnimator a minor issue with that approach is that the debug.sethook call itself isn't covered. Perhaps luacov should expose a wrapper function instead, e.g.

```lua
if not jit then -- LuaJIT does not support per-coroutine debug hooks
   local wrap; wrap = cqueues.interpose("wrap", function(self, func, ...)
      func = luacov.runner.with_luacov(func)
      return wrap(self, func, ...)
   end)
end
```

**Comment by daurnimator** [comment]
Perhaps the luajit check should be in luacov?

**Comment by mpeterv** [comment]
@daurnimator sure, that would make sense

**Comment by mpeterv** [comment]
@daurnimator under LuaJIT on master branch luacov now doesn't patch coroutine functions and in #42 with_luacov() doesn't call debug.sethook.

**Comment by daurnimator** [comment]
Thanks. that's helpful.
