### ISSUE TITLE
Large slowdown

### ISSUE THREAD

**Issue by benbarbour** [keplerproject/luacov#46]
Programs run with `require("luacov")` are taking about 3.5 times longer to execute than without that require. Is this expected and does anyone think it might be possible to speed it up?

To be clear, I wouldn't be surprised at all if this is normal, it's just that we have a lot of timing sensitive tests that currently fail when run with luacov enabled so I'm hoping that it's not normal.

**Comment by mpeterv** [comment]
Some slowdown is expected because luacov uses a debug hook that runs every time Lua executes a line of code. I'll see if the overhead can be reduced.

**Comment by mpeterv** [comment]
I'd reduced the overhead of the debug hook a little on master branch, can you try it?

**Comment by mpeterv** [comment]
I've released luacov 0.12.0 and [cluacov](https://github.com/mpeterv/cluacov) which contains implementation of debug hook in C. I get 3x-4x speedup on most tests using it. I don't think it's possible to improve performance using pure Lua.
