### ISSUE TITLE
[question]is there any way to use luacov in c++ project with lua vm

### ISSUE THREAD

**Issue by ostack** [keplerproject/luacov#53]
[question]is there any way to use luacov in c++ project with lua vm

In my project we creat a lua vm when we run the program,and we use this lua vm to execute lua script use lua function luaL_dostring(). so i wonder if there is any way to use luacov to generate coverage report when run the porgram.
Additionally ,as our lua script will call c++ function api to query data, so we can not use `lua xxx.lua` to execute the lua script.

THKS

**Comment by mpeterv** [comment]
It is possible to load `luacov` from a C/C++ project, either by bundling its source files or embedding them into C/C++ files directly. Then you can call `init()` function from `luacov.runner` module to start collecting coverage data. it will set a debug hook for that.

When a line is executed, the hook needs to understand from which file it came. It relies on chunk name of the function containing the line for that. Normally files loaded with `dofile` and `require` have chunk names starting with `@`, and the rest is file name. So by default the hook considers only lines with such chunk names. If `codefromstrings` configuration option is set to `true`, it will consider lines without `@`, too. `luaL_dostring` sets chunk name to the source string itself, you may want to use `luaL_loadbuffer` to have better control over it.

Before terminating, call `shutdown()` function from `luacov.runner` module to stop collecting coverage data and save it to `luacov.stats.out` file.

The main problem is viewing collected data. The base reporter assumes that all the covered Lua strings exist as files. It also has some logic to determine what lines in these files can be hit at all. E.g. if a line is empty, it should not be marked as missed in coverage report. It has to read the files to determine that. 

So you'd have to ensure that all strings for which coverage is gathered can also be accessed as files, and use `luacov` command line tool to make a report. E.g. if a string is loaded with `@foo/bar.lua` or `foo/bar.lua` chunkname, it should be also in a file named `foo/bar.lua` when `luacov` tool is run.

You could also use `load` from `luacov.stats` module to get raw coverage data from `luacov.stats.out` and then print it out in some way.

**Comment by ostack** [comment]
In order to call luacov.runner.init() and shutdown() function, I write a lua script in a file, read and do the script when i start/finish  my  collecting coverage data, but there is no stat.out file generate.
Is this usage correct or should i call init()/ shutdown() function in my c++ code?

**Comment by mpeterv** [comment]
Yes, it should work like that. If there is no output file generated, maybe it's in some other directory if the program changed current directory before calling `shutdown()`, or maybe the debug hook is overwritten in C++ code. How exactly are you calling `luacov.runner.init()`? Do you pass `codefromstrings` through `.luacov` file or by passing configuration table to `init()`?

**Comment by ostack** [comment]
my lua code and config file like below,and config file luacovConfig.lua is in my lua path :

`local dataApi = require("DataApi")
local runner = require("luacov.runner")
local luaCovState=dataApi.query({xpath="/Me:Me",fields={}}) --use c++ interface to query data 
if (#luaCovState > 0) then
    for i=1,#luaCovState do
        local dataVal = luaCovState[i].value
        local luaCovState = dataVal.luaCovState --get luaCovState value
        if ( (luaCovState == "init") ) then
            runner.init("luacovConfig.lua")  --init with special file
        elseif ( (luaCovState == "shutdown")) then
            runner.shutdown()
        end
    end 
end`


“luacovConfig.lua”：

--- Default values for configuration options.
-- For project specific configuration create '.luacov' file in your project
-- folder. It should be a Lua script setting various options as globals
-- or returning table of options.
-- @class module
-- @name luacov.defaults
return {

  --- Filename to store collected stats. Default: "luacov.stats.out".
  statsfile = "luacov.stats.out",

  --- Filename to store report. Default: "luacov.report.out".
  reportfile = "luacov.report.out",

  --- Enable saving coverage data after every `savestepsize` lines?
  -- Setting this flag to `true` in config is equivalent to running LuaCov
  -- using `luacov.tick` module. Default: false.
  tick = false,

  --- Stats file updating frequency for `luacov.tick`.
  -- The lower this value - the more frequently results will be written out to the stats file.
  -- You may want to reduce this value (to, for example, 2) to avoid losing coverage data in
  -- case your program may terminate without triggering luacov exit hooks that are supposed
  -- to save the data. Default: 100.
  savestepsize = 10,

  --- Run reporter on completion? Default: false.
  runreport = false,

  --- Delete stats file after reporting? Default: false.
  deletestats = false,
  
  --- Process Lua code loaded from raw strings?
  -- That is, when the 'source' field in the debug info
  -- does not start with '@'. Default: false.
  codefromstrings = true,

  --- Lua patterns for files to include when reporting.
  -- All will be included if nothing is listed.
  -- Do not include the '.lua' extension. Path separator is always '/'.
  -- Overruled by `exclude`.
  include = {},

  --- Lua patterns for files to exclude when reporting.
  -- Nothing will be excluded if nothing is listed.
  -- Do not include the '.lua' extension. Path separator is always '/'.
  -- Overrules `include`.
  exclude = {},

  --- Table mapping names of modules to be included to their filenames.
  -- Has no effect if empty.
  -- Real filenames mentioned here will be used for reporting
  -- even if the modules have been installed elsewhere.
  -- Module name can contain '*' wildcard to match groups of modules,
  -- in this case corresponding path will be used as a prefix directory
  -- where modules from the group are located.
  -- @usage
  -- modules = {
  --    ["some_rock"] = "src/some_rock.lua",
  --    ["some_rock.*"] = "src"
  -- }
  modules = {},

}

**Comment by ostack** [comment]
ha ha it works finally,thanks very much .

summarize how to use in c++ function, hope useful for others
1. luacov can be use in c++ project. It is better to use luaL_dofile() or luaL_loadbuffer() to load and execute lua script in the project ,as  luacov use the lua script file to generate the report 
2. when use luaL_dofile() or luaL_loadbuffer() the file path better to be absolute.
3. when use luaL_loadbuffer() the **codefromstrings** parameter in luacov.default.lua should be true.
4. before start collecting coverage data ,we should call runner.init() to init luacov,and call runner.shutdown() before stop collecting coverage data. After this it will generate lua coverage file "luacov.stats.out" in the exe running dir.

**Comment by vivian2011** [comment]
@ZhaoGuangYue1986  how about android and ios？
