### ISSUE TITLE
Comment to skip coverage per block or line

### ISSUE THREAD

**Issue by LPGhatguy** [keplerproject/luacov#54]
Sometimes I have branches that I don't really care about coverage for, but having a bright red mark on the line/file in Coveralls is a shame.

A feature to have inline configuration comments would be useful, like:

```lua
-- luacov: disable block
if DEBUG_SETTING_ONLY then
    -- I don't care if this code is covered by tests, it's for specific circumstances!
    print("Debug mode enabled!")
end
```

If block parsing is too difficult in the context of luacov (and I imagine it is), this would be pretty handy:

```lua
if DEBUG_SETTING_ONLY then
    -- luacov: disable
    -- debug stuff here
    -- luacov: enable
end
```

**Comment by mpeterv** [comment]
A bit late, but I've implemented the second variation on master branch. Parsing blocks is indeed difficult in luacov, would need to import a full lexer/parser. Luacov does some limited lexing that allows it to figure out comments like that.

A new version with this feature will be released soon, within a week most likely.

**Comment by LPGhatguy** [comment]
Is there a succinct change log for 0.13 available anywhere?
