### ISSUE TITLE
luacov.shutdown doesn't really shutdown properly

### ISSUE THREAD

**Issue by KayleMaster** [keplerproject/luacov#58]
```lua
                  
require 'busted.runner' ()

_G.lcov = require'luacov'
lcov.excludetree('.')
lcov.includefile('objects/objects.lua')
local ob = require 'objects.objects'  
...
tests
...
lcov.save_stats()
lcov.shutdown()
```
And I get 0% coverage for objects/objects.lua
Immediately after this the applications calls a function which exits the program.
If I remove lcov.shutdown everything works and I get proper readings. Any idea?

**Comment by mpeterv** [comment]
I can't reproduce this strange behaviour with the coverage being saved without `lcov.shutdown()` but not saved with it. What version of `luacov` and `busted` are you using?

I'm attempting to reproduce with this code:

```lua
require 'busted.runner' ()

_G.lcov = require'luacov'
lcov.excludetree('.')
lcov.includefile('objects/objects.lua')
local ob = require 'objects.objects'

it("test", function()
   ob.test()
end)

lcov.save_stats()
lcov.shutdown()
```

And `objects/objects.lua` is

```lua
local objects = {}

function objects.test()
   print("In objects.test()")
end

return objects
```

**Comment by KayleMaster** [comment]
@mpeterv 

Latest busted and luacov via luarocks.
With lcov.shutdown only with one file tested - objects in this case - returns false coverage. It's like the tests busted did, didn't affect coverage for some reason. I get 33% coverage with shutdown, but only because that's the code executed when the module is required.

Here is what I want to do:  
I have two files to test:
objects, terrain
I test them with two files:
objects_spec
terrain_spec
Where objects_spec is loaded first.
In objects_spec I do (after I require luacov)
```
lcov.excludetree('.')
lcov.includefile('objects.lua')
```
So that I only test that file (it may call functions from other files, but that will result in false coverage)
I do lcov.shutdown/lcov.save_stats at the end of the file to generate the stats file that should have only the coverage for this file.
Moving on to terrain, I do the same thing but it won't work. Whatever I do only objects is included in the report. I also don't want to include objects.lua this time, because terrain calls a function from objects and that again will result in false coverage. 
lcov.shutdown/save_stats is called at the end of terrain_spec and the stats are ADDED to luacov.stats.out.
So now I should have objects and terrain in luacov.stats.out legit coverage. Is this possible or do I need to modify your library?

**Comment by KayleMaster** [comment]
Nevermind.
