### ISSUE TITLE
Get invalid coverage report

### ISSUE THREAD

**Issue by ktalebian** [keplerproject/luacov#69]
I cloned this repo, and tried to run the `spec/nested` coverage report test using:

```bash
rm luacov.*
lua -lluacov test.lua
luacov 
```

This generated a `luacov.report.out` that matched [expected.out](https://github.com/keplerproject/luacov/blob/master/spec/nested/expected.out). 

Then `test.lua` to be

```lua
local testlib = require "testlib"
local luacov = require "luacov.runner"

testlib.f1()
```

i.e. just include the `testlib`, call method `f1` but don't run any tests. Re-running the luacoverage report, I now get the following output:

```
==============================================================================
testlib.lua
==============================================================================
 1 local a = 1
 1 local b = 2

 1 local lib = {}

 1 function lib.f1()
 1    local c = 3
 1    return 4
   end

 1 function lib.f2()
*0    local d = 5
*0    return 6
   end

 1 return lib

==============================================================================
Summary
==============================================================================

File        Hits Missed Coverage
--------------------------------
testlib.lua 8    2      80.00%
--------------------------------
Total       8    2      80.00%
```

It is saying that I have a coverage of 80%, which I do not; the mere act of `require` the test file into the test file is causing it to be counted as covered test.

**Comment by hishamhm** [comment]
it is correct: 80% of the lines were covered. The percentage does not indicate the percentage of _functions_ covered, but that of lines.

**Comment by ktalebian** [comment]
That ... seems like a really terrible test coverage reporting. Test coverage should cover the number of source code lines that were actually tested, not called.

**Comment by hishamhm** [comment]
What is you definition of "tested"?
