### ISSUE TITLE
Reporting untested files

### ISSUE THREAD

**Issue by dread-uo** [keplerproject/luacov#70]
Hello! I have a bunch of untested files on my project, and the report shows a total percentage of coverage regarding only the files touched by the tests. I tried putting more files on the `include` configuration table, but my untested files don't get reported. Do you know how could I do this?

**Comment by hishamhm** [comment]
@dread-uo unfortunately, LuaCov does not currently have this feature. It only reports files that were executed by the Lua VM. I believe it would not be too hard to write a patch to add this feature!

**Comment by dread-uo** [comment]
It seems there are 2 pull requests implementing this; will one of them be merged soon?

**Comment by hishamhm** [comment]
@dread-uo #71 is now merged, thanks for the nudge!

**Comment by dread-uo** [comment]
@hishamhm , hello again! Could you release a new version of `luacov` on LuaRocks with those this feature?
Thanks in advance o/
