### ISSUE TITLE
luacov to collect coverage for .nse script

### ISSUE THREAD

**Issue by ColleenLee1102** [keplerproject/luacov#79]
Can I use luacov to collect coverage for .nse script?
nse script is interpreted by an integrated Lua interpreter with nmap.

**Comment by hishamhm** [comment]
I'm not familiar with the nmap scripting environment, but the following things need to be supported:

* it needs to support `require` to load Lua modules
* it needs to support the standard `debug` library from Lua to add line counting hooks
* it needs to support the standard `io` library from Lua to save the coverage data

If all three are true, then it should be possible to run `require"luacov"` and enable collecting of coverage data.

Hope this answers the question!
