### ISSUE TITLE
merge two stats result for the same file

### ISSUE THREAD

**Issue by magicsupery** [keplerproject/luacov#86]
when i run unit-test, i must set a new env for the whole project, if i want to test the game.lua coverage, can i do this :

1. init the env
2. `lua -lluacov game.lua`
3. copy the status.out to stats.out.1
4. init the env
5. `lua -lluacov game.lua`
6. copy the status.out to status.out.2

then i use a scirpt, add the number of the same pos in the status.out, then i use luacov to got the report?
is this a correct report?

**Comment by hishamhm** [comment]
@magicsupery if you simply copy the status file from the first env to the second env, luacov will add the results automatically. No need to use different names and combine with a script!

Hope that helps!
